name: Safe Settings Sync
on:
  workflow_dispatch: {}

jobs:
  safeSettingsSync:
    runs-on: ubuntu-latest
    env:
      # Version/tag of github/safe-settings repo to use:
      SAFE_SETTINGS_VERSION: 2.1.17

      # Path on GHA runner box where safe-settings code downloaded to:
      SAFE_SETTINGS_CODE_DIR: ${{ github.workspace }}/.safe-settings-code
      SAFE_SETTINGS_GH_ORG: abhipost12
      SAFE_SETTINGS_APP_ID: 2504975
      SAFE_SETTINGS_GITHUB_CLIENT_ID: Iv23liQzqPSR3ew9BLSu
      
      
    steps:
      # Self-checkout of 'admin' repo for access to safe-settings config:
      - uses: actions/checkout@v4

      # Checkout of safe-settings repo for running full sync:
      - uses: actions/checkout@v4
        with:
          repository: github/safe-settings
          ref: ${{ env.SAFE_SETTINGS_VERSION }}
          path: ${{ env.SAFE_SETTINGS_CODE_DIR }}
      - uses: actions/setup-node@v4
      - run: npm install
        working-directory: ${{ env.SAFE_SETTINGS_CODE_DIR }}
      - name: Run docker-compose
        env:
          GH_ORG: abhipost12
          APP_ID: 2504975
          PRIVATE_KEY: ${{ secrets.SAFE_SETTINGS_PRIVATE_KEY }}
          GITHUB_CLIENT_ID: Iv23liQzqPSR3ew9BLSu
          GITHUB_CLIENT_SECRET: ${{ secrets.SAFE_SETTINGS_GITHUB_CLIENT_SECRET }}
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        run: docker compose up -d
        
